namespace NewLMS.UMKM.Domain.Dwh.Entities
{
    public class PH_GABUNGAN
    {
        public DateTime BUSS_DATE {get;set;}
        public string ID_WO {get;set;}
        public string NO_SURAT {get;set;}
        public string TGL_SURAT {get;set;}
        public string NO_CLAIM {get;set;}
        public string TGL_CLAIM {get;set;}
        public string BUNGA_DITERIMA {get;set;}
        public string BRANCH_SMBR_DANA {get;set;}
        public string CIF_SMBR_DANA {get;set;}
        public string SUFFIX_SMBR_DANA {get;set;}
        public DateTime TGL_WO {get;set;}
        public string KODE_CABANG {get;set;}
        public string KODE_KCP {get;set;}
        public string LOAN_TYPE {get;set;}
        public string DEAL_REF {get;set;}
        public string CIF {get;set;}
        public string NAMA_DEBITUR {get;set;}
        public string ALAMAT1 {get;set;}
        public string ALAMAT2 {get;set;}
        public string ALAMAT3 {get;set;}
        public string ALAMAT4 {get;set;}
        public string ALAMAT5 {get;set;}
        public DateTime TANGGAL_REALISASI {get;set;}
        public DateTime TANGGAL_JATUH_TEMPO {get;set;}
        public string JENIS_KREDIT {get;set;}
        public string NO_PK {get;set;}
        public string DIVISI {get;set;}
        public string DIVISIONID {get;set;}
        public string TENOR {get;set;}
        public int PLAFOND_KREDIT {get;set;}
        public string KOLEKTOABILITAS {get;set;}
        public int NILAI_KOLATERAL_WO {get;set;}
        public int NILAI_KOLATERALCPRNT {get;set;}
        public int SISA_POKOK_PENGHAPUSAN {get;set;}
        public int SISA_POKOK_PELAPORAN {get;set;}
        public int BUNGA_PENGHAPUSAN {get;set;}
        public int BUNGA_PELAPORAN {get;set;}
        public int BUNGA_EKSTRA_PENGHAPUSAN {get;set;}
        public int BUNGA_EKSTRA_PELAPORAN {get;set;}
        public int DENDA_PENGHAPUSAN {get;set;}
        public int DENDA_PELAPORAN {get;set;}
        public int PENALTY_PRICIPAL_ADJ {get;set;}
        public int PENALTY_INTERERST_ADJ {get;set;}
        public int JUMLAH_PENGAPUSAN {get;set;}
        public int JUMLAH_PELAPORAN {get;set;}
        public string SEKTOR_EKONOMI {get;set;}
        public string PERSENTASE_BUNGA {get;set;}
        public string MATA_UANG {get;set;}
        public string JENIS_PH {get;set;}
        public string NPWP {get;set;}
        public string BADAN_USAHA {get;set;}
        public string ASURANSI {get;set;}
        public string PRESENTASE {get;set;}
        public string BESAR_CLAIM {get;set;}
        public string SUBROGASI {get;set;}
        public string RECOVERSI {get;set;}
        public string HAK_ASRNSI_BLN_INI {get;set;}
        public string JENIS_AGUNAN {get;set;}
        public string JUMLAH_AGUNAN {get;set;}
        public string PENINGKATAN_AGUNAN {get;set;}
        public string NO_TELEPON {get;set;}
        public string AVALIST {get;set;}
        public string SEBAB_KEMACETAN {get;set;}
        public string KOMITMEN_DEBITUR {get;set;}
        public string POTENSI_PENYELESAIAN {get;set;}
        public string ACTION_PLAN_CBG {get;set;}
        public string PEMUTUS {get;set;}
        public string ANALIST {get;set;}
        public string JML_PNRIMAAN_BLN_INI {get;set;}
        public string KETERANGAN_SETOR {get;set;}
        public string POSISI {get;set;}
        public string NARATIVE {get;set;}
        public DateTime TANGGAL_PH {get;set;}
        public string JENIS_PENGGUNAAN {get;set;}
        public string FLAG_LUNAS {get;set;}
        public string KODE_USER {get;set;}
        public DateTime TANGGAL_UPDATE {get;set;}
        public string DATA_SOURCE {get;set;}

    }
}