pipeline 
{
    agent any
    environment 
    {
        dotnet = 'C:\\Program Files\\dotnet\\dotnet.exe'
    }
    # $Env:ASPNETCORE_ENVIRONMENT = "Development"
    # dotnet ef database update -c UserContext -p NewLMS.Umkm.Domain -s NewLMS.Umkm.API
    stages 
    {
        stage('Checkout Stage') 
        {
          steps 
          {
            git credentialsId: 'b5a3d387-bb6b-4847-b206-477ecc0d4834', url: 'https://gitlab.com/bjb-lms/bjb-lms-backend.git', branch: 'main'   
          }
        }
        stage('Restore packages') 
        {
          steps 
          {
            bat "dotnet restore NewLMS.Umkm.sln"
          }
        }
        stage("Release Stage") 
        {
          steps 
          {
              bat 'dotnet publish -c Release'
          }
        }
        stage("Stop IIS 192.168.232.248")
        {
            steps 
            {
                sshPublisher(publishers: [sshPublisherDesc(configName: 'NEWLMS248', transfers: [
                  sshTransfer(cleanRemote: false, 
                  excludes: '', 
                  execCommand: 'net stop "W3SVC"', 
                  execTimeout: 120000, 
                  flatten: false, 
                  makeEmptyDirs: false, 
                  noDefaultExcludes: false, 
                  patternSeparator: '[, ]+', 
                  remoteDirectory: '', 
                  remoteDirectorySDF: false, 
                  removePrefix: '', 
                  sourceFiles: '', 
                  useSftpForExec: false)], 
                  usePromotionTimestamp: false, 
                  useWorkspaceInPromotion: false, 
                  verbose: true)])
            }
        }
        stage("Stop IIS 192.168.232.249")
        {
            steps 
            {
                sshPublisher(publishers: [sshPublisherDesc(configName: 'NEWLMS249', transfers: [
                  sshTransfer(cleanRemote: false, 
                  excludes: '', 
                  execCommand: 'net stop "W3SVC"', 
                  execTimeout: 120000, 
                  flatten: false, 
                  makeEmptyDirs: false, 
                  noDefaultExcludes: false, 
                  patternSeparator: '[, ]+', 
                  remoteDirectory: '', 
                  remoteDirectorySDF: false, 
                  removePrefix: '', 
                  sourceFiles: '', 
                  useSftpForExec: false)], 
                  usePromotionTimestamp: false, 
                  useWorkspaceInPromotion: false, 
                  verbose: true)])
            }
        }
        stage("Copy File To Server 192.168.232.248")
        {
          steps 
          {
              //Deploy application on IIS
              sshPublisher(publishers: [sshPublisherDesc(configName: 'NEWLMS248', transfers: [
                sshTransfer(
                cleanRemote: true, 
                excludes: '**/NewLMS.Umkm.API/bin/Release/net6.0/publish/appsettings.Production.json', 
                execCommand: '', 
                execTimeout: 120000, 
                flatten: false, 
                makeEmptyDirs: false, 
                noDefaultExcludes: false, 
                patternSeparator: '[, ]+', 
                remoteDirectory: '/', 
                remoteDirectorySDF: false, 
                removePrefix: 'NewLMS.Umkm.API/bin/Release/net6.0/publish/', 
                sourceFiles:  '**/NewLMS.Umkm.API/bin/Release/net6.0/publish/*', 
                useSftpForExec: true)], 
                usePromotionTimestamp: false, 
                useWorkspaceInPromotion: false, 
                verbose: true)])
          }
        }
        stage("Copy File To Server 192.168.232.249")
        {
          steps 
          {
              //Deploy application on IIS
              sshPublisher(publishers: [sshPublisherDesc(configName: 'NEWLMS249', transfers: [
                sshTransfer(
                cleanRemote: true, 
                excludes: '**/NewLMS.Umkm.API/bin/Release/net6.0/publish/appsettings.Production.json', 
                execCommand: '', 
                execTimeout: 120000, 
                flatten: false, 
                makeEmptyDirs: false, 
                noDefaultExcludes: false, 
                patternSeparator: '[, ]+', 
                remoteDirectory: '/', 
                remoteDirectorySDF: false, 
                removePrefix: 'NewLMS.Umkm.API/bin/Release/net6.0/publish/', 
                sourceFiles:  '**/NewLMS.Umkm.API/bin/Release/net6.0/publish/*', 
                useSftpForExec: true)], 
                usePromotionTimestamp: false, 
                useWorkspaceInPromotion: false, 
                verbose: true)])
          }
        }
        stage("Start IIS 192.168.232.248")
        {
            steps 
            {
                //Deploy application on IIS
                sshPublisher(publishers: [sshPublisherDesc(configName: 'NEWLMS248', transfers: [
                  sshTransfer(cleanRemote: false, 
                  excludes: '', 
                  execCommand: 'NET START "W3SVC"', 
                  execTimeout: 120000, 
                  flatten: false, 
                  makeEmptyDirs: false, 
                  noDefaultExcludes: false, 
                  patternSeparator: '[, ]+', 
                  remoteDirectory: '', 
                  remoteDirectorySDF: false, 
                  removePrefix: '', 
                  sourceFiles: '', 
                  useSftpForExec: false)], 
                  usePromotionTimestamp: false, 
                  useWorkspaceInPromotion: false, 
                  verbose: true)])
            }
        }
        stage("Start IIS 192.168.232.249")
        {
            steps 
            {
                //Deploy application on IIS
                sshPublisher(publishers: [sshPublisherDesc(configName: 'NEWLMS249', transfers: [
                  sshTransfer(cleanRemote: false, 
                  excludes: '', 
                  execCommand: 'NET START "W3SVC"', 
                  execTimeout: 120000, 
                  flatten: false, 
                  makeEmptyDirs: false, 
                  noDefaultExcludes: false, 
                  patternSeparator: '[, ]+', 
                  remoteDirectory: '', 
                  remoteDirectorySDF: false, 
                  removePrefix: '', 
                  sourceFiles: '', 
                  useSftpForExec: false)], 
                  usePromotionTimestamp: false, 
                  useWorkspaceInPromotion: false, 
                  verbose: true)])
            }
        }
    }
}